Hyp 1281
devtron-labs/kubelink pull request #4
Opened 2022-03-14 12:37 UTC by manish-agrawal-ai

2022-03-21 07:32 UTC, nishant-d requested changes

2022-03-21 07:32 UTC, nishant-d commented on pkg/helmClient/client.go
> +func mergeRollbackOptions(chartSpec *ChartSpec, rollbackOptions *action.Rollback) {
attach function with class

2022-03-21 09:41 UTC, vikramdevtron commented on pkg/service/HelmAppServiceWrapper.go
> +	impl.Logger.Infow("Rollback release request", "clusterName", releaseIdentifier.ClusterConfig.ClusterName, "releaseName", releaseIdentifier.ReleaseName,
can we change, info > debug

2022-03-21 12:02 UTC, manish-agrawal-ai commented on pkg/helmClient/client.go
> +func mergeRollbackOptions(chartSpec *ChartSpec, rollbackOptions *action.Rollback) {
This is utility function.

2022-03-21 12:02 UTC, manish-agrawal-ai commented on pkg/service/HelmAppServiceWrapper.go
> +	impl.Logger.Info("Rollback release request served")
Will discuss this

2022-03-21 12:03 UTC, manish-agrawal-ai commented on pkg/service/HelmAppServiceWrapper.go
> +	impl.Logger.Infow("Rollback release request", "clusterName", releaseIdentifier.ClusterConfig.ClusterName, "releaseName", releaseIdentifier.ReleaseName,
Will discuss this

2022-03-23 06:16 UTC, pghildiyal commented on pkg/helmClient/client.go
> +func mergeRollbackOptions(chartSpec *ChartSpec, rollbackOptions *action.Rollback) {
this is not merge, this is copy

2022-03-23 06:22 UTC, manish-agrawal-ai commented on pkg/helmClient/client.go
> +func mergeRollbackOptions(chartSpec *ChartSpec, rollbackOptions *action.Rollback) {
done.

2022-03-23 06:46 UTC, nishant-d approved these changes

2022-03-23 06:46 UTC, merged